/**
 * ファイルツリーで使用する Catppuccin アイコン名を解決するユーティリティ。
 *
 * `@iconify-json/catppuccin` のアイコンセットに対応する。
 * アイコン名は `catppuccin:<name>` の形式で使用する。
 */

/** ファイル名（完全一致）→ アイコン名のマッピング。 */
const FILE_NAME_MAP: Record<string, string> = {
  'package.json': 'package-json',
  'package-lock.json': 'npm-lock',
  'pnpm-lock.yaml': 'pnpm-lock',
  'yarn.lock': 'yarn-lock',
  'bun.lock': 'bun-lock',
  'cargo.lock': 'cargo-lock',
  'dub.selections.json': 'dub-selections',
  'tsconfig.json': 'typescript-config',
  'jsconfig.json': 'javascript-config',
  '.eslintrc': 'eslint',
  '.eslintignore': 'eslint-ignore',
  '.prettierrc': 'prettier',
  '.prettierignore': 'prettier-ignore',
  '.gitignore': 'git',
  '.gitattributes': 'git',
  '.gitmodules': 'git',
  '.editorconfig': 'editorconfig',
  '.env': 'env',
  '.envrc': 'envrc',
  '.npmignore': 'npm-ignore',
  '.npmrc': 'npm',
  '.nvmrc': 'npm',
  Dockerfile: 'docker',
  'docker-compose.yml': 'docker-compose',
  'docker-compose.yaml': 'docker-compose',
  '.dockerignore': 'docker-ignore',
  Makefile: 'makefile',
  makefile: 'makefile',
  GNUmakefile: 'makefile',
  LICENSE: 'license',
  'LICENSE.md': 'license',
  'LICENSE.txt': 'license',
  CHANGELOG: 'changelog',
  'CHANGELOG.md': 'changelog',
  'CHANGELOG.txt': 'changelog',
  CONTRIBUTING: 'contributing',
  'CONTRIBUTING.md': 'contributing',
  'CODE_OF_CONDUCT.md': 'code-of-conduct',
  CODEOWNERS: 'codeowners',
  '.cursorrules': 'cursor',
  '.cursorignore': 'cursor-ignore',
  'biome.json': 'biome',
  'biome.jsonc': 'biome',
};

/** ファイル名のプレフィックス（前方一致）→ アイコン名のマッピング。 */
const FILE_PREFIX_MAP: Record<string, string> = {
  README: 'readme',
  'vite.config': 'vite',
  'vitest.config': 'vitest',
  'eslint.config': 'eslint',
  'prettier.config': 'prettier',
  'tailwind.config': 'tailwind',
  'postcss.config': 'postcss',
  'rollup.config': 'rollup',
  'webpack.config': 'webpack',
  'babel.config': 'babel',
  'jest.config': 'jest',
  'playwright.config': 'playwright',
  'cypress.config': 'cypress',
  'next.config': 'next',
  'nuxt.config': 'nuxt',
  'astro.config': 'astro',
  'svelte.config': 'svelte',
  'wrangler.config': 'wrangler',
  '.eslintrc': 'eslint',
  '.prettierrc': 'prettier',
  '.stylelintrc': 'stylelint',
  'stylelint.config': 'stylelint',
  'electron-builder': 'config',
  'electron.vite.config': 'vite',
};

/** 拡張子 → アイコン名のマッピング。 */
const EXTENSION_MAP: Record<string, string> = {
  ts: 'typescript',
  tsx: 'typescript-react',
  'ts.snap': 'typescript-test',
  mts: 'typescript',
  cts: 'typescript',
  'd.ts': 'typescript-def',
  js: 'javascript',
  jsx: 'javascript-react',
  mjs: 'javascript',
  cjs: 'javascript',
  json: 'json',
  jsonc: 'json',
  json5: 'json',
  yaml: 'yaml',
  yml: 'yaml',
  toml: 'toml',
  md: 'markdown',
  mdx: 'markdown-mdx',
  html: 'html',
  css: 'css',
  scss: 'sass',
  sass: 'sass',
  less: 'less',
  svg: 'svg',
  png: 'image',
  jpg: 'image',
  jpeg: 'image',
  gif: 'image',
  webp: 'image',
  ico: 'favicon',
  sh: 'bash',
  bash: 'bash',
  zsh: 'bash',
  fish: 'bash',
  py: 'python',
  pyc: 'python-compiled',
  rs: 'rust',
  go: 'go',
  rb: 'ruby',
  java: 'java',
  kt: 'kotlin',
  swift: 'swift',
  c: 'c',
  h: 'c-header',
  cpp: 'cpp',
  cc: 'cpp',
  'h++': 'cpp-header',
  hpp: 'cpp-header',
  cs: 'csharp',
  php: 'php',
  r: 'r',
  dart: 'dart',
  lua: 'lua',
  vim: 'vim',
  ex: 'elixir',
  exs: 'elixir',
  erl: 'erlang',
  hrl: 'erlang',
  hs: 'haskell',
  elm: 'elm',
  clj: 'clojure',
  cljs: 'clojure',
  ml: 'ocaml',
  mli: 'ocaml',
  fs: 'fsharp',
  fsx: 'fsharp',
  scala: 'scala',
  zig: 'zig',
  nim: 'nim',
  vue: 'vue',
  svelte: 'svelte',
  astro: 'astro',
  graphql: 'graphql',
  gql: 'graphql',
  proto: 'proto',
  sql: 'database',
  db: 'database',
  tf: 'terraform',
  tfvars: 'terraform',
  xml: 'xml',
  plist: 'xml',
  csv: 'csv',
  txt: 'text',
  log: 'log',
  lock: 'lock',
  env: 'env',
  key: 'key',
  pem: 'certificate',
  crt: 'certificate',
  cer: 'certificate',
  p12: 'certificate',
  pdf: 'pdf',
  zip: 'zip',
  tar: 'zip',
  gz: 'zip',
  rar: 'zip',
  '7z': 'zip',
  exe: 'exe',
  mp3: 'audio',
  wav: 'audio',
  ogg: 'audio',
  flac: 'audio',
  mp4: 'video',
  mov: 'video',
  avi: 'video',
  webm: 'video',
  wasm: 'web-assembly',
  bat: 'batch',
  cmd: 'batch',
  ps1: 'powershell',
  psm1: 'powershell',
};

/** フォルダ名（完全一致、大文字小文字区別なし）→ アイコン名ベースのマッピング。 */
const FOLDER_NAME_MAP: Record<string, string> = {
  src: 'src',
  source: 'src',
  components: 'components',
  hooks: 'hooks',
  lib: 'lib',
  libs: 'lib',
  utils: 'utils',
  util: 'utils',
  helpers: 'utils',
  styles: 'styles',
  style: 'styles',
  css: 'styles',
  types: 'types',
  type: 'types',
  assets: 'assets',
  public: 'public',
  static: 'public',
  dist: 'dist',
  build: 'dist',
  out: 'dist',
  output: 'dist',
  node_modules: 'node',
  '.node_modules': 'node',
  tests: 'tests',
  test: 'tests',
  __tests__: 'tests',
  spec: 'tests',
  __mocks__: 'mocks',
  mocks: 'mocks',
  docs: 'docs',
  doc: 'docs',
  documentation: 'docs',
  config: 'config',
  configs: 'config',
  '.config': 'config',
  scripts: 'scripts',
  script: 'scripts',
  api: 'api',
  server: 'server',
  client: 'client',
  shared: 'shared',
  common: 'shared',
  middleware: 'middleware',
  routes: 'routes',
  route: 'routes',
  pages: 'app',
  app: 'app',
  images: 'images',
  img: 'images',
  icons: 'svg',
  svg: 'svg',
  fonts: 'fonts',
  font: 'fonts',
  '.github': 'github',
  '.gitlab': 'gitlab',
  '.vscode': 'vscode',
  '.cursor': 'cursor',
  '.devcontainer': 'devcontainer',
  '.husky': 'husky',
  workflows: 'workflows',
  '.github/workflows': 'workflows',
  database: 'database',
  db: 'database',
  migrations: 'database',
  views: 'views',
  controllers: 'controllers',
  models: 'database',
  layouts: 'layouts',
  plugins: 'plugins',
  packages: 'packages',
  core: 'core',
  features: 'core',
  modules: 'core',
  audio: 'audio',
  video: 'video',
  download: 'download',
  downloads: 'download',
  upload: 'upload',
  uploads: 'upload',
  temp: 'temp',
  tmp: 'temp',
  cache: 'temp',
  coverage: 'coverage',
  storybook: 'storybook',
  '.storybook': 'storybook',
  queue: 'queue',
  content: 'content',
  locales: 'locales',
  locale: 'locales',
  i18n: 'locales',
  translations: 'locales',
  android: 'android',
  ios: 'macos',
  macos: 'macos',
  linux: 'linux',
  windows: 'windows',
  security: 'security',
  private: 'private',
  git: 'git',
  '.git': 'git',
  next: 'next',
  nuxt: 'nuxt',
  firebase: 'firebase',
  docker: 'docker',
  kubernetes: 'kubernetes',
  k8s: 'kubernetes',
  aws: 'aws',
  azure: 'azure-devops',
  gcp: 'cloud',
  cloud: 'cloud',
  functions: 'functions',
  lambda: 'functions',
  tauri: 'tauri',
  electron: 'vscode',
  redux: 'redux',
  graphql: 'graphql',
  prisma: 'prisma',
  benchmarks: 'benchmark',
  benchmark: 'benchmark',
  examples: 'examples',
  example: 'examples',
  sample: 'examples',
  templates: 'templates',
  template: 'templates',
  turbo: 'turbo',
  proto: 'proto',
  include: 'include',
  composables: 'composables',
  renovate: 'renovate',
  '.renovate': 'renovate',
  admin: 'admin',
  audit: 'audit',
  connection: 'connection',
  constant: 'constant',
  constants: 'constant',
  symlink: 'symlink',
  animation: 'animation',
  animations: 'animation',
  themes: 'themes',
  theme: 'themes',
  sym: 'symlink',
  command: 'command',
  commands: 'command',
  handlers: 'command',
  services: 'server',
  repositories: 'database',
  repository: 'database',
};

/**
 * ファイル名からアイコン名を解決する。
 *
 * @param name - ファイル名（例: `"App.tsx"`, `"package.json"`）
 * @returns Iconify アイコン ID（例: `"catppuccin:typescript-react"`）
 */
export function getFileIconName(name: string): string {
  // 完全一致
  if (FILE_NAME_MAP[name]) {
    return `catppuccin:${FILE_NAME_MAP[name]}`;
  }

  // プレフィックス一致
  for (const [prefix, icon] of Object.entries(FILE_PREFIX_MAP)) {
    if (name.startsWith(prefix)) {
      return `catppuccin:${icon}`;
    }
  }

  // 拡張子で解決（複合拡張子を先に試みる）
  const dotIndex = name.indexOf('.');
  if (dotIndex !== -1) {
    const ext = name.slice(dotIndex + 1);
    if (EXTENSION_MAP[ext]) {
      return `catppuccin:${EXTENSION_MAP[ext]}`;
    }
    const simpleExt = name.split('.').pop() ?? '';
    if (EXTENSION_MAP[simpleExt]) {
      return `catppuccin:${EXTENSION_MAP[simpleExt]}`;
    }
  }

  return 'catppuccin:file';
}

/**
 * フォルダ名からアイコン名を解決する。
 *
 * @param name - フォルダ名（例: `"src"`, `"node_modules"`）
 * @param isOpen - フォルダが展開されているかどうか
 * @returns Iconify アイコン ID（例: `"catppuccin:folder-src-open"`）
 */
export function getFolderIconName(name: string, isOpen: boolean): string {
  const lowerName = name.toLowerCase();
  const base = FOLDER_NAME_MAP[lowerName] ?? FOLDER_NAME_MAP[name];
  if (base) {
    return isOpen ? `catppuccin:folder-${base}-open` : `catppuccin:folder-${base}`;
  }
  return isOpen ? 'catppuccin:folder-open' : 'catppuccin:folder';
}
